version: "3.8"
   
services:
  db:
    image: postgres:13.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-j54wkw)ofm#*xm*574!!nnw0u==(_dzj%=ylvu@1)0pa1(r7-p
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db